# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Yapi MCP Pro
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts
# Copy source and build
COPY . .
RUN npm run build

# Final image
FROM node:lts-alpine
WORKDIR /app
# Copy built files and production deps
COPY package.json package-lock.json .
RUN npm install --production --ignore-scripts
COPY --from=builder /app/dist ./dist
# Expose default port (for HTTP mode, though we run stdio)
EXPOSE 3388
ENTRYPOINT ["node", "dist/index.js"]
