# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy all files and build
COPY . .
RUN npm run build

# Expose default port (if used by HTTP mode)
EXPOSE 3388

ENV NODE_ENV=cli

CMD ["node", "dist/cli.js", "--stdio"]
